program ::= statement* Eof;

sep_list[$item, $sep=","] ::= $item ($sep $item)*;
list[$item, $sep=","] ::= sep_list[$item, $sep] $sep?;

statement ::=
  | assignment ";"
  | (Ident ":")? block_expr
  | declaration
  | expr ";"
  ;

# Ambiguity resolved in precedence.md
expr ::=
  | unary_op expr
  | expr binary_op expr
  | "[" list["..."? expr] "]"
  | "(" tuple_elements? ")"
  | expr ("." | "?.") Ident
  | expr "?."? "[" expr "]"
  | expr "!"
  | expr "?."? "(" list["..."? expr]? ")"
  | expr "?" expr ":" expr
  | expr "is" type
  | ("async" | "const")? "(" params ")" "=>" (expr | statement_block)
  | "return" expr?
  | "throw" expr?
  | "break" (":" Ident)? expr?
  | "continue" (":" Ident)?
  | (Ident ":")? block_expr
  | NoSubTemplate
  | TemplateHead (expr TemplateMiddle)* expr TemplateTail
  | IntLiteral
  | FloatLiteral
  | Ident
  | "(" expr ")"
  ;

block_expr ::=
  | "do" block
  | "if" "(" expr ")" block ("else" "if" "(" expr ")" block)* ("else" block)?
  | "match" "(" expr ")" "{" match_arms? "}"
  | "loop" block
  | "while" "(" expr ")" block
  | "for" "(" for_header ")" block
  | "try" block ("catch" ("(" pattern ")")? block ("finally" block)? | "finally" block)
  ;

declaration ::=
  | variable_declaration ";"
  | ("const" | "async")? "function" "(" params? ")" statement_block
  ;

variable_declaration ::= ("let" | "const") pattern "=" expr;

tuple_elements ::= (expr ",")+ expr?

for_header ::=
  | (variable_declaration | assignment | expr)? ";" expr? ";" (assignment | expr)?
  | pattern "in" expr
  ;

params ::= list[pattern];

block ::= "{" statement* expr? "}";
statement_block ::= "{" statement* "}";

match_arms ::=
  (match_arm_head (block_expr ","? | expr ","))*
  match_arm_head expr ","?
  ;

match_arm_head ::= match_pattern ("if" expr)? "=>";

match_pattern ::= sep_list[expr | type object_pattern, "|"];

pattern ::=
  | Ident
  | object_pattern
  | array_pattern
  ;

object_pattern ::= "{" list[Ident (":" pattern)? ("=" expr)?]? "}";

array_pattern ::= "[" list[pattern | "..." Ident]? "]";

assignment ::= assignable assignment_op expr;

# Uses same precedence levels as expr
assignable ::=
  | expr "." Ident
  | expr "[" expr "]"
  | pattern
  ;

unary_op ::= "-" | "!" | "~" | "await";

binary_op ::=
  | "??"
  | "||"
  | "&&"
  | "==" | "!="
  | "<" | "<=" | ">" | ">="
  | "|"
  | "^"
  | "&"
  | "<<" | ">>"
  | "+" | "-"
  | "*" | "/" | "%"
  | "**"
  ;

assignment_op ::=
  | "="
  | "+=" | "-="
  | "*=" | "/=" | "%="
  | "**="
  | "&=" | "^=" | "|="
  | "&&=" | "||="
  | "<<=" | ">>="
  | "??="
  ;

type ::=
  |
  ;
